### ISSUE TITLE
Option to not fetch query

### ISSUE THREAD

**Issue by thunder-red-star** [mcstatus-io/node-mcstatus#2]
Feature request: I'm using this for a Discord bot to detect changes in my server's uptime and I don't want to fetch query. Any way to pass in an options object where query is disabled?

Would have implemented it myself but the formatting rules seem pretty strict and I don't want to screw them up.

**Comment by PassTheMayo** [comment]
This library was released before query support was added to the API, so I completely forgot to add that feature to this library.

I'll get this added to the library sometime later today when I'm available, but I'll let you know when it's published. Thank you for reminding me to add this.

**Comment by PassTheMayo** [comment]
Just published version `1.1.0` to npm which adds an options argument to `statusJava()` which should allow you to disable query. Thank you for your feedback.
