### ISSUE TITLE
BaseURL option doesn't actually work...

### ISSUE THREAD

**Issue by RahulR100** [mcstatus-io/node-mcstatus#5]
Hey there!

I saw the recent update that added the baseURL option and I think this is a wonderful addition! However, when I tried to use it, it does not do anything. I found that this is due to hardcoded values from the node-mcstatus/dist/enum.d.ts file being read into the dist/status.d.ts file (which is what is then imported). Unsure if this is just the new source code (from node-mcstatus/src) not being built yet or if there are additional steps that need to be taken here?

**Comment by PassTheMayo** [comment]
I published version `v1.2.1` about two weeks ago that should have resolved this issue. It was because the package was not re-built before publishing.
